name: sentence-embedder.apis.miku.gg

on:
  push:
    branches:
      - master
    paths:
      - apps/embeddings-apis/sentence-embedder
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY_SENTENCE_EMBEDDER }}
        HOST: ${{ secrets.EC2_HOST_SENTENCE_EMBEDDER }}
        USER: ${{ secrets.EC2_USER_SENTENCE_EMBEDDER }}
        SERVICE_NAME: "sentence-embedder"
        DOMAIN_SUBDOMAIN: "sentence-embedder.apis.miku.gg"
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem" -avz --exclude '.git' apps/embeddings-apis/sentence-embedder/ $USER@$HOST:/home/$USER/$SERVICE_NAME
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem $USER@$HOST "sudo apt-get install -y python3-pip"
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem $USER@$HOST "pip3 install -r /home/$USER/$SERVICE_NAME/requirements.txt"
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem $USER@$HOST "sudo systemctl stop $DOMAIN_SUBDOMAIN.service"
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem $USER@$HOST "cd $SERVICE_NAME && gunicorn --bind 127.0.0.1:8080 app:app &"
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem $USER@$HOST "sudo systemctl start $DOMAIN_SUBDOMAIN.service"
